config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'feed#show'

  # Users
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  resource :profile, only: %i[show update], controller: 'users'
  namespace :users do
    patch 'change_password', to: 'passwords#update'
    resources :password_resets, only: %i[new create edit update]
  end

  # sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :listings, except: :index
  resource :my_listings, only: :show
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord
  include PermittedAttributes
  include HasAddress
  include AccessPolicy

  # Enum
  enum :condition, {
    mint: 'mint',
    near_mint: 'near_mint',
    used: 'used',
    defective: 'defective'
  }

  # Associations
  belongs_to :organization
  belongs_to :creator, class_name: 'User'
  has_one_attached :photo
  has_rich_text :description

  # Validations
  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :condition, presence: true
  validates :tags, length: { in: 1..5 }
  validates :photo, presence: true
  validates :description, presence: true

  # Callbacks
  before_save :downcase_tags

  # Scopes
  scope :feed, lambda {
    order(created_at: :desc)
      .includes(:address)
      .with_attached_cover_photo
  }

  private

  def downcase_tags
    self.tags = tags.map(&:downcase)
  end
end

app/models/listing/access_policy.rb
# frozen_string_literal: true

module Listing::AccessPolicy
  def show?
    true
  end

  def edit?
    organization == Current.organization
  end

  def update?
    organization == Current.organization
  end

  def destroy?
    organization == Current.organization
  end

  def can_save?
    organization != Current.organization
  end

  def can_contact?
    organization != Current.organization
  end
end

app/models/listing/permitted_attributes.rb
# frozen_string_literal: true

module Listing::PermittedAttributes
  extend ActiveSupport::Concern

  class_methods do
    def permitted_attributes
      [
        :title, :price, :condition, :photo, :description,
        {
          tags: [],
          address_attributes: Address.permitted_attributes
        }
      ]
    end
  end
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  before_action :load_listing, except: %i[new create]

  allow_unauthenticated only: :show

  def new
    @listing = Listing.new
    @listing.build_address
  end

  def create
    @listing = Listing.new(
      listing_params.with_defaults(
        creator: Current.user,
        organization: Current.organization
      )
    )

    if @listing.save
      flash[:success] = t('.success')
      recede_or_redirect_to(listing_path(@listing), status: :see_other)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def show; end

  def edit; end

  def update
    if @listing.update(listing_params)
      flash[:success] = t('.success')
      recede_or_redirect_to(listing_path(@listing), status: :see_other)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @listing.destroy!
    flash[:success] = t('.success')
    recede_or_redirect_to(my_listings_path, status: :see_other)
  end

  private

  def listing_params
    params.require(:listing).permit(
      Listing.permitted_attributes
    )
  end

  def load_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
# frozen_string_literal: true

module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="block">
  <%= form.label :title, class: 'label' %>
  <%= form.text_field :title, class: 'input is-large' %>
</div>

<%= render 'shared/image_field',
           form: form,
           attribute: :photo,
           field_label: t('.photo') %>

<layout-columns class="columns is-centered ml-5 mr-5">
  <layout-column class="box column is-half mt-6 p-5 m-4">
    <div class="is-flex is-flex-direction-column">
      <form-field class="field">
        <%= form.label :price, class: 'label' %>
        <form-field class="field has-addons">
          <p class="control">
            <a href="#" class="button is-static">£</a>
          </p>

          <p class="control is-expanded">
            <%= form.text_field :price,
                                inputmode: :numeric,
                                class: 'input' %>
          </p>
        </form-field>
      </form-field>

      <form-field class="field">
        <%= form.label :condition, class: 'label' %>
        <div class="select is-fullwidth">
          <%= form.select :condition,
                          Listing.human_enum_options(:condition) %>
        </div>
      </form-field>

      <form-field class="field">
        <%= render 'tags_field', form: form %>
      </form-field>

      <form-field class="field">
        <%= form.label :address, class: 'label is-large' %>
        <div class="box">
          <%= render 'addresses/fields', form: form %>
        </div>
      </form-field>
    </div>
  </layout-column>

  <layout-column class="box column is-half mt-6 p-5 m-4">
    <form-field class="field">
      <%= form.label :description, class: 'label' %>
      <%= form.rich_text_area :description %>

      <%= tag.p class: 'help is-danger' do %>
        <%= form.object.errors.message_for(:description).to_sentence %>
      <% end if form.object.errors.include?(:description) %>
    </form-field>
  </layout-column>
</layout-columns>

app/views/listings/_listing.html.erb
<div class="card">
  <div class="card-image">
    <%= link_to listing_path(listing) do %>
      <figure class="image is-4by3">
        <% if listing.photo.present? %>
          <%= image_tag listing.photo.variant(resize_to_fit: [500, 500]), loading: :lazy %>
        <% end %>
      </figure>
    <% end %>
  </div>

  <div class="card-content is-block">
    <article class="content">
      <%= link_to listing_path(listing) do %>
        <h1 class="title mb-2">
          <%= listing.title %>
        </h1>
      <% end %>

      <%= render 'listings/tags', listing: listing %>

      <dl class="block">
        <dd class="has-text-weight-semibold is-size-5 m-0">
          ￡<%= listing.price %>
        </dd>
        <dd class="tag is-link has-text-weight-semibold m-0">
          <span class="icon-text is-align-items-center">
            <%= svg_tag('location',
                        class: 'icon is-small mr-2',
                        fill: '#444'
                ) %>
            <span>
              <%= listing.address&.redacted %>
            </span>
          </span>
        </dd>
      </dl>
    </article>
  </div>
</div>

app/views/listings/_tag.html.erb
<% form = local_assigns[:form] %>

<ui-tag class="control tags has-addons" data-controller="remove-element">
  <%= tag.span class: 'tag is-primary' do %>
    #<%= value %>
  <% end %>

  <% if form.present? %>
    <%= form.fields_for(:tags) do |fields| %>
      <%= fields.hidden_field nil, id: nil, value: value %>
    <% end %>

    <%= tag.a class: 'tag is-primary is-delete',
              data: { action: 'remove-element#remove' } %>
  <% end %>
</ui-tag>

app/views/listings/_tags.html.erb
<%= tag.layout_container(
  class: 'field is-grouped is-grouped-multiline',
  data: {
    tags_target: 'container'
  }
) do %>
  <% listing.tags&.each do |value| %>
    <%= render 'listings/tag', value: value %>
  <% end %>
<% end %>

app/views/listings/_tags_field.html.erb
<form-field class="field" data-controller="tags">
  <%= form.label :tags, class: 'label' %>
  <p class="has-text-weight-medium has-text-grey is-italic mb-2">
    <%= t('.description') %>
  </p>

  <%= tag.layout_container(
    class: 'field is-grouped is-grouped-multiline',
    data: { tags_target: 'container' }
  ) do %>
    <% form.object.tags.each do |value| %>
      <%= render 'tag', value: value, form: form %>
    <% end if form.object.tags.present? %>
  <% end %>

  <form-field class="field is-grouped">
    <div class="control is-expanded">
      <%= text_field_tag nil, nil,
                         class: 'input',
                         data: { tags_target: 'input' } %>
    </div>

    <div class="control">
      <button class="button is-info" type="button" data-action="tags#addTag">
        <%= t('.add_tag') %>
      </button>
    </div>
  </form-field>

  <%= tag.p class: 'help is-danger' do %>
    <%= form.object.errors.messages_for(:tags).to_sentence %>
  <% end %>

  <template data-tags-target="template">
    <%= render 'tag', value: "{value}", form: form %>
  </template>
</form-field>

app/views/listings/edit.html.erb
<%= content_for(:title) do %>
  <%= @listing.title %>
<% end %>

<layout-columns class="columns is-centered">
  <%= form_with(
        model: @listing,
        class: 'column is-10',
        id: 'edit_listing_form'
      ) do |form| %>
    <%= render 'form', form: form %>
  <% end %>
</layout-columns>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <layout-group class="buttons is-right">
      <%= button_to t('.delete'),
                    listing_path(@listing),
                    method: :delete,
                    form: { data: {
                      turbo_confirm: t('.confirm_delete')
                    } },
                    class: 'button is-danger is-medium m-3' unless turbo_native_app? %>
      <%= submit_tag t('.publish'),
                     form: 'edit_listing_form',
                     class: 'button is-primary is-medium m-3' %>
    </layout-group>
  </layout-column>
</layout-columns>

app/views/listings/new.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>

<layout-columns class="columns is-centered">
  <%= form_with(
        model: @listing,
        class: 'column is-10',
        id: 'new_listing_form'
      ) do |form| %>
    <%= render 'form', form: form %>
  <% end %>
</layout-columns>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <layout-group class="buttons is-right">
      <%= submit_tag t('.publish'),
                     form: 'new_listing_form',
                     class: 'button is-primary is-medium m-3' %>
    </layout-group>
  </layout-column>
</layout-columns>

app/views/listings/show.html.erb
<%= content_for(:title) do %>
  <%= @listing.title %>
<% end %>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <% tag.div class: "mb-3" do %>
      <h1 class="title is-inline">
        <%= @listing.title %>
      </h1>

      <% if @listing.edit? %>
        <%= link_to t('.edit'), edit_listing_path(@listing) %>
      <% end %>
    <% end unless turbo_native_app? %>

    <%= render 'tags', listing: @listing %>

    <div class="has-text-centered">
      <%= link_to url_for(@listing.photo) do %>
        <figure class="image is-inline-block">
          <%= image_tag @listing.photo.variant(resize_to_limit: [800, 800]) %>
        </figure>
      <% end %>
    </div>

    <layout-columns class="columns is-centered">
      <layout-column class="box column is-half mt-6 p-5 m-4">
        <dl>
          <dt class="has-text-grey">
            <%= t('.posted_by') %>
          </dt>
          <dd class="has-text-weight-semi-bold is-size-5">
            <%= @listing.creator.name %>
          </dd>

          <br/>

          <dt class="has-text-grey">
            <%= t('.location') %>
          </dt>
          <dd class="has-text-weight-semibold is-size-5">
            <%= @listing.address.redacted %>
          </dd>
        </dl>

        <layout-group class="buttons mt-6">
          <%= button_to '#', class: 'button is-secondary is-medium' do %>
            <%= svg_tag("heart", class: "icon is-small mr-3") %>
            <%= t('.save') %>
          <% end %>

          <%= link_to '#', class: 'button is-primary is-medium' do %>
            <%= svg_tag("message", class: 'icon is-small mr-3', fill: '#fff') %>
            <%= t('.contact') %>
          <% end %>
        </layout-group>
      </layout-column>

      <layout-column class="box column mt-6 p-5 m-4">
        <dl>
          <dt class="has-text-grey">
            <%= Listing.human_attribute_name(:price) %>
          </dt>
          <dd class="has-text-weight-semibold is-size-5">
            <%= "￡#{@listing.price}" %>
          </dd>

          <br/>

          <dt class="has-text-grey">
            <%= Listing.human_attribute_name(:condition) %>
          </dt>
          <dd class="has-text-weight-semibold is-size-5">
            <%= @listing.human_enum_value(:condition) %>
          </dd>

          <br>

          <dt class="has-text-grey">
            <%= Listing.human_attribute_name(:description) %>
          </dt>
          <dd class="mt-3">
            <%= @listing.description %>
          </dd>
        </dl>
      </layout-column>
    </layout-columns>
  </layout-column>
</layout-columns>

<% if turbo_native_app? && @listing.edit? %>
  <%= link_to t(".edit"),
              edit_listing_path(@listing),
              data: {
                controller: "bridge--element",
                bridge_element_id:
                  turbo_native_bridge_element_id(:edit),
                bridge_element_ios: {
                  component: "bar_button",
                  icon: "pencil",
                  index: "0"
                }.to_json,
                bridge_element_android: {
                  component: "menu_item",
                  order: "0"
                }.to_json
              } %>

  <%= button_to t(".delete"),
                listing_path(@listing),
                method: :delete,
                data: {
                  controller: "bridge--element",
                  bridge_element_id:
                    turbo_native_bridge_element_id(:delete),
                  bridge_element_ios: {
                    component: "bar_button",
                    icon: "trash",
                    index: "1"
                  }.to_json,
                  bridge_element_android: {
                    component: "menu_item",
                    order: "1"
                  }.to_json
                },
                form: {
                  data: {
                    turbo_confirm: t("listings.edit.confirm_delete")
                  }
                } %>
<% end %>