config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'feed#show'

  # Users
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  resource :profile, only: %i[show update], controller: 'users'
  namespace :users do
    patch 'change_password', to: 'passwords#update'
    resources :password_resets, only: %i[new create edit update]
  end

  # sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :listings, except: :index
  resource :my_listings, only: :show
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  include PermittedAttributes

  attribute :country, default: 'GB'

  # Associations
  belongs_to :addressable, polymorphic: true

  # Validations
  validates :line1, presence: true
  validates :line2, presence: true
  validates :city, presence: true
  validates :postcode, presence: true
  validates :country, presence: true

  def redacted
    "#{city}, #{postcode}"
  end
end

app/models/app_session.rb
# frozen_string_literal: true

class AppSession < ApplicationRecord
  # token will be auto generated in before_create callback and hence optional field.
  has_secure_password :token, validations: false

  # associations
  belongs_to :user

  # callbacks
  before_create do
    self.token = self.class.generate_unique_secure_token
  end

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token:
    }
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  include HumanEnum
  include MessageVerifier

  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user, :app_session, :organization
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord
  include PermittedAttributes
  include HasAddress
  include AccessPolicy

  # Enum
  enum :condition, {
    mint: 'mint',
    near_mint: 'near_mint',
    used: 'used',
    defective: 'defective'
  }

  # Associations
  belongs_to :organization
  belongs_to :creator, class_name: 'User'
  has_one_attached :photo
  has_rich_text :description

  # Validations
  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :condition, presence: true
  validates :tags, length: { in: 1..5 }
  validates :photo, presence: true
  validates :description, presence: true

  # Callbacks
  before_save :downcase_tags

  # Scopes
  scope :feed, lambda {
    order(created_at: :desc)
      .includes(:address)
      .with_attached_cover_photo
  }

  private

  def downcase_tags
    self.tags = tags.map(&:downcase)
  end
end

app/models/membership.rb
# frozen_string_literal: true

class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  # associations
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  has_many :listings, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include PasswordReset
  include Authentication

  # validations
  validates :name, presence: true
  validates :email,
            format: { with: URI::MailTo::EMAIL_REGEXP },
            uniqueness: { case_sensitive: false }

  # associations
  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  # callbacks
  before_validation :strip_extraneous_spaces

  private

  def strip_extraneous_spaces
    self.name = name&.strip
    self.email = email&.strip
  end
end

app/controllers/feed_controller.rb
# frozen_string_literal: true

class FeedController < ApplicationController
  allow_unauthenticated

  def show
    @pagy, @listings = pagy(Listing.feed)
  end
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  before_action :load_listing, except: %i[new create]

  allow_unauthenticated only: :show

  def new
    @listing = Listing.new
    @listing.build_address
  end

  def create
    @listing = Listing.new(
      listing_params.with_defaults(
        creator: Current.user,
        organization: Current.organization
      )
    )

    if @listing.save
      flash[:success] = t('.success')
      recede_or_redirect_to(listing_path(@listing), status: :see_other)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def show; end

  def edit; end

  def update
    if @listing.update(listing_params)
      flash[:success] = t('.success')
      recede_or_redirect_to(listing_path(@listing), status: :see_other)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    @listing.destroy!
    flash[:success] = t('.success')
    recede_or_redirect_to(my_listings_path, status: :see_other)
  end

  private

  def listing_params
    params.require(:listing).permit(
      Listing.permitted_attributes
    )
  end

  def load_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_authentication only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      @organization = Organization.create!(members: [@user])
      @app_session = @user.app_sessions.create!
      log_in(@app_session)

      flash[:success] = t('.welcome', name: @user.name)
      recede_or_redirect_to(root_path, status: :see_other)
    else
      Rails.logger.debug { "Error: #{@user.errors.messages}" }
      render(:new, status: :unprocessable_entity)
    end
  end

  def show
    @user = Current.user
  end

  def update
    @user = Current.user

    if @user.update(update_params)
      flash[:success] = t('.success')
      redirect_to(profile_path, status: :see_other)
    else
      render(:show, status: :unprocessable_entity)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def title
    return t('piazza') unless content_for?(:title)
    return content_for(:title) if turbo_native_app?

    "#{content_for(:title)} | #{t('piazza')}"
  end
end

app/helpers/feed_helper.rb
# frozen_string_literal: true

module FeedHelper
end

app/helpers/listings_helper.rb
# frozen_string_literal: true

module ListingsHelper
end

app/helpers/my_listings_helper.rb
# frozen_string_literal: true

module MyListingsHelper
end

app/helpers/pagination_helper.rb
# frozen_string_literal: true

module PaginationHelper
  def show_paginator?
    !turbo_native_app? && instance_variable_get(:@pagy).pages > 1
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/svg_helper.rb
# frozen_string_literal: true

module SvgHelper
  def svg_tag(svg_name, **attributes)
    svg_markup = render(file: Rails.root.join("app/views/shared/svg/#{svg_name}.svg"))

    xml = Nokogiri::XML(svg_markup)
    attributes&.each do |key, value|
      xml.root.set_attribute(key, value)
    end

    # rubocop:disable Rails/OutputSafety
    xml.root.to_xml.html_safe
    # rubocop:enable Rails/OutputSafety
  end
end

app/helpers/turbo_native_helper.rb
# frozen_string_literal: true

module TurboNativeHelper
  MAX_INT = 2**30 - 1
  private_constant :MAX_INT

  def turbo_native_bridge_platform
    case request.user_agent
    when /Turbo Native iOS/
      'ios'
    when /Turbo Native Android/
      'android'
    else
      ''
    end
  end

  def turbo_native_bridge_element_id(identifier)
    Zlib.crc32(identifier.to_s, MAX_INT)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' unless turbo_native_app? %>
    <%= render 'shared/flashes' %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pagy/_nav.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<%#                            -%>
<nav class="pagy-bulma-nav pagination is-centered"
     role="navigation"
     aria-label="pagination">

  <% if pagy.prev -%>
    <%== link.call(
           pagy.prev,
           pagy_t('pagy.nav.prev'),
           'class="pagination-previous" aria-label="previous page"'
         ) %>
  <% else -%>
    <a class="pagination-previous" disabled>
      <%== pagy_t('pagy.nav.prev') %>
    </a>
  <% end -%>

  <% if pagy.next -%>
    <%== link.call(
           pagy.next,
           pagy_t('pagy.nav.next'),
           'class="pagination-next" aria-label="next page"'
         ) %>
  <% else -%>
    <a class="pagination-next" disabled><%== pagy_t('pagy.nav.next') %></a>
  <% end -%>

  <ul class="pagination-list">
    <%# series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]        -%>
    <% pagy.series.each do |item| %>
      <% if item.is_a?(Integer) -%>
        <li>
          <%== link.call item,
                         item,
                         %(class="pagination-link" aria-label="goto page #{item}") %>
        </li>
      <% elsif item.is_a?(String) -%>
        <li>
          <%== link.call item,
                         item,
                         %(class="pagination-link is-current" aria-label="page #{item}" aria-current="page") %>
        </li>
      <% elsif item == :gap -%>
        <li>
          <span class="pagination-ellipsis">
            <%== pagy_t('pagy.nav.gap') %>
          </span>
        </li>
      <% end -%>
    <% end -%>
  </ul>
</nav>

app/views/shared/_flashes.html.erb
<div class="container is-fluid" data-turbo-temporary>
  <% flash.each do |level, message| %>
    <%= tag.div class: "notification is-#{level} is-light has-text-centered mt-4" do %>
      <%= message %>
    <% end %>
  <% end %>
</div>

app/views/shared/_image_field.html.erb
<%= tag.image_upload_field(
  data: {
    controller: 'image-upload',
    image_upload_blob_url_template_value: rails_service_blob_url(
      ':signed_id', ':filename'
    )
  }
) do %>
  <div class="file is-large is-boxed is-centered">
    <label class="file-label" data-image-upload-target="cta">
      <%= form.file_field(
            nil,
            id: nil,
            class: 'file_input',
            accept: 'image/*',
            direct_upload: true,
            required: true,
            data: {
              action: 'image-upload#upload',
              image_upload_target: 'fileInput'
            }
          ) %>
      <%= form.hidden_field(
            attribute,
            value: form.object.photo&.signed_id,
            data: {
              image_upload_target: 'hiddenInput'
            }
          ) %>
      <span class="file-cta">
        <%= svg_tag('upload', class: 'file-icon') %>
        <span class="file-label">
          <%= field_label %>
        </span>
      </span>
    </label>
  </div>

  <figure class="image is-relative">
    <% url = form.object.photo.present? ? url_for(form.object.photo) : '' %>
    <%= image_tag url, data: { image_upload_target: 'preview' } %>
  </figure>

  <progress
    value="0"
    max="100"
    class="progress is-primary"
    data-image-upload-target="progress"
  ></progress>

  <%= tag.div(
    class: 'buttons is-centered is-hidden mt-3',
    data: {
      image_upload_target: 'remove'
    }
  ) do %>
    <%= tag.button(
      class: 'button is-danger',
      type: 'button',
      data: { action: 'image-upload#remove' }
    ) do %>
      <%= t('.remove_image') %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-link" data-controller="navbar">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <strong class="is-size-3">Piazza</strong>
    <% end %>

    <a role="button"
       class="navbar-burger"
       data-navbar-target="burger"
       data-action="navbar#toggle">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>

  <navbar-menu class="navbar-menu" data-navbar-target="menu">
    <div class="navbar-start">
      <%= link_to t('.create_ad'), new_listing_path, class: 'navbar-item' %>
      <%= link_to t('.messages'), '#', class: 'navbar-item' if logged_in? %>
    </div>

    <div class="navbar-end">
      <%= tag.div class: 'navbar-item has-dropdown is-hoverable mr-4' do %>
        <%= link_to Current.user.name,
                    profile_path,
                    id: 'current_user_name',
                    class: "navbar-link" %>

        <div class="navbar-dropdown is-right">
          <%= link_to t(".profile"),
                      profile_path,
                      id: 'current_user_name',
                      class: 'navbar-item' %>
          <%= link_to t(".my_ads"), my_listings_path, class: 'navbar-item' %>
          <%= link_to t(".saved_ads"), '#', class: 'navbar-item' %>
          <hr class="navbar-divider">
          <%= link_to t(".logout"),
                      logout_path,
                      class: 'navbar-item',
                      data: { turbo_method: :delete } %>
        </div>
      <% end if logged_in? %>

      <%= tag.div class: "navbar-item" do %>
        <div class="buttons">
          <%= link_to t('.sign_up'), sign_up_path, class: 'button is-primary' %>

          <%= link_to t('.login'), login_path, class: 'button is-light' %>
        </div>
      <% end unless logged_in? %>
    </div>
  </navbar-menu>
</nav>